      BLOCK DATA INIT
      INTEGER BOARD(120)
      COMMON /PLRDAT/ BOARD
      DATA BOARD /120*0/ 

      INTEGER EMPTY, OFFBRD
      INTEGER WPAWN, WKNIGHT, WBISH, WROOK, WQUEN, WKING
      INTEGER BPAWN, BKNIGHT, BBISH, BROOK, BQUEN, BKING

      PARAMETER (EMPTY=0, OFFBRD=99)
      PARAMETER (WPAWN=1, WKNIGHT=2, WBISH=3, WROOK=4, WQUEN=5, WKING=6)
      PARAMETER (BPAWN=-1, BKNIGHT=-2, BBISH=-3, BROOK=-4, BQUEN=-5, BKI
     +NG=-6)
      END

      PROGRAM MAIN
      INTEGER BOARD(120)
      INTEGER GETIDX
      COMMON /PLRDAT/ BOARD
      CALL INIBRD
      WRITE(*,800) GETIDX(1,1)
  800 FORMAT(I3)
      END

      SUBROUTINE INIBRD
      INTEGER EMPTY, OFFBRD
      INTEGER WPAWN, WKNIGHT, WBISH, WROOK, WQUEN, WKING
      INTEGER BPAWN, BKNIGHT, BBISH, BROOK, BQUEN, BKING
      PARAMETER (EMPTY=0, OFFBRD=99)
      PARAMETER (WPAWN=1, WKNIGHT=2, WBISH=3, WROOK=4, WQUEN=5, WKING=6)
      PARAMETER (BPAWN=-1, BKNIGHT=-2, BBISH=-3, BROOK=-4, BQUEN=-5, BKI
     +NG=-6)

      INTEGER GETIDX
      INTEGER BOARD(120)
      COMMON /PLRDAT/ BOARD
      DO 10 I = 1, 120
         BOARD(I) = OFFBRD
   10 CONTINUE

      DO 30 IRANK = 1, 8
         DO 20 IFILE = 1, 8
            I = GETIDX(IRANK,IFILE)
            BOARD(I) = EMPTY
   20    CONTINUE
   30 CONTINUE

      DO 40 IFILE = 1,8
        I = GETIDX(2,IFILE)
        BOARD(I) = WPAWN 
        I = GETIDX(7,IFILE)
        BOARD(I) = BPAWN
   40 CONTINUE
      END

      FUNCTION GETIDX(RANK,FILE)
        INTEGER RANK,FILE, GETIDX
        GETIDX = (RANK+1) * 10 + (FILE+1)
      END 

      SUBROUTINE MAKMOV(FROM,TOWARD)
        INTEGER EMPTY 
        PARAMETER(EMPTY=0)
        INTEGER FROM, TOWARD 
        INTEGER BOARD(120) 
        COMMON /PLRDAT/ BOARD 
        BOARD(TOWARD) = BOARD(FROM)
        BOARD(FROM) = EMPTY
      END 
      SUBROUTINE PRSNMV(CMD)
      INTEGER GETIDX
      CHARACTER*(*) CMD
      INTEGER I1, I2, F1, R1, F2, R2
    
      F1 = ICHAR(CMD(1:1)) - ICHAR('a') + 1
      R1 = ICHAR(CMD(2:2)) - ICHAR('0')
      F2 = ICHAR(CMD(3:3)) - ICHAR('a') + 1
      R2 = ICHAR(CMD(4:4)) - ICHAR('0')

      I1 = GETIDX(R1,F1)
      I2 = GETIDX(R1,F1)

      CALL MAKMOV(I1, I2)
      END